### ISSUE TITLE
what is bufo

### ISSUE THREAD

**Issue by andyshinn** [knobiknows/all-the-bufo#13]

**Comment by knobiknows** [comment]
Bufo also known as Froge or Concerned Frog refers to a set of Discord emotes of a worried or concerned frog expressing various emotions, similar to Pepe emotes. The frog image comes from the now-inactive mobile game Froge, released in 2014 by Fandom Inc. and became popularized as a set of Discord emotes starting in 2020. In 2023, a Froge ChatGPT plugin launched.
