### ISSUE TITLE
Bufo

### ISSUE THREAD

**Issue by GrantBirki** [knobiknows/all-the-bufo#14]
How does bufo have so many unique personalities, characteristics, and traits?

**Comment by knobiknows** [comment]
100s of people have contributed to this repo and imbued bufo with their own personalities and moods. Many of them also combo bufo with othre pre-existing memes. 

:be-the-bufo-you-want-to-see:
![image](https://github.com/knobiknows/all-the-bufo/assets/116683796/9c8ddaee-dbb6-4684-b1fd-1f28eb542967)
