### ISSUE TITLE
why did you name him bufo 

### ISSUE THREAD

**Issue by SoymilkSky** [knobiknows/all-the-bufo#21]
only have ever known this emote to be `froge` or `worryfroge`

noticed my company has these emotes on slack named `bufo-something` so I went on a quest to find out where it came from and it led me here

I would like to know why it's named bufo

**Comment by knobiknows** [comment]
I saw `froge` being used on some Discords but it probably had too many Pepe/4chan connotations for a work environment. [Bufo](https://en.wikipedia.org/wiki/Common_toad) seemed like an obvious and neutral choice.
