### ISSUE TITLE
A few custom creations to add

### ISSUE THREAD

**Issue by bendebnam** [knobiknows/all-the-bufo#22]
Thanks so much for the resource!  I've got a few custom ones, quite proud of the lightsaber ones, who knew all this time learning after effects was for gifs 15 years on. 

![bufo-awkward-eyes](https://github.com/knobiknows/all-the-bufo/assets/1911263/30423639-dc5b-4ae0-aeb2-32a3e01fd8d4)
![bufo-confetti](https://github.com/knobiknows/all-the-bufo/assets/1911263/3077e566-e9d3-46ca-b5c6-2a56ecc3b135)
![bufo-judge](https://github.com/knobiknows/all-the-bufo/assets/1911263/840b09f1-a9ae-4eab-9841-592c60de051f)
![bufo-star-wars-lightsaber-jedi](https://github.com/knobiknows/all-the-bufo/assets/1911263/8fe744d3-e49c-4974-b0dd-36c4d62e3fb4)
![bufo-star-wars-lightsaber-sith](https://github.com/knobiknows/all-the-bufo/assets/1911263/cde27702-3bd1-4ce1-8557-877d14684713)

**Comment by knobiknows** [comment]
Lovely stuff :)

Do you want to make a PR or should I add them to the repo, @bendebnam ?

**Comment by knobiknows** [comment]
all files added
