### ISSUE TITLE
Bufo gives star

### ISSUE THREAD

**Issue by milena-markovic** [knobiknows/all-the-bufo#23]
Inspired by a lovely teammate that sends ⭐ emojis as praise for a job well done, I present you with :bufo-gives-star:

![bufo-gives-star](https://github.com/knobiknows/all-the-bufo/assets/46020779/bcaae32d-cd13-47be-a01c-781a8ea4cc87)

(I'm not sure how to get permissions to push to this repo so I'll just leave it here)

**Comment by knobiknows** [comment]
added to the repo
