### ISSUE TITLE
a few good bufos looking for a home

### ISSUE THREAD

**Issue by jeremy-wiker** [knobiknows/all-the-bufo#24]
I have a goal to take regularly used (traditional) emojis at my organization and bufo-fy them. Hope these newbies can find a new home:
![bufo-10-4](https://github.com/knobiknows/all-the-bufo/assets/84956139/bc7d5936-3462-4670-8980-5e5f63277a19)
![bufo-fistbump](https://github.com/knobiknows/all-the-bufo/assets/84956139/f11bfe28-b40c-4bf0-9a64-8eb2f591845e)

**Comment by knobiknows** [comment]
:bufo-has-been-added-to-your-OKRs:
