### ISSUE TITLE
Are Bufo’s hands canonically fingered or mittened?

### ISSUE THREAD

**Issue by dylanatsmith** [knobiknows/all-the-bufo#26]
[Fingered](https://github.com/knobiknows/all-the-bufo/blob/main/all-the-bufo/bufo-thanks.png) or [mittened](https://github.com/knobiknows/all-the-bufo/blob/main/all-the-bufo/bufo-welp.png)?

**Comment by knobiknows** [comment]
Well, whenever you notice something like that, a wizard did it.

![image](https://github.com/knobiknows/all-the-bufo/raw/main/all-the-bufo/bufo-exit.gif)
