### ISSUE TITLE
big bufo should be bigbufo_row_column rather than column_row

### ISSUE THREAD

**Issue by amorisot** [knobiknows/all-the-bufo#34]
<img width="517" alt="image" src="https://github.com/user-attachments/assets/68d1a5c0-dc9e-4a56-ae2c-59b1cff9e2e7">

**Comment by giannis2two** [comment]
Yes

**Comment by marwanad** [comment]
+1

**Comment by knobiknows** [comment]
fixed by @jaybonthius
